<?php
/**
 * Modulation Report Web Display
 * 
 * Displays the optimized modulation report data generated by 
 * modulation_report_generator.py in a nice web interface

 */

// Configuration
$REPORT_DIR = 'reports';
$DEFAULT_DATE = date('Y-m-d');

// Get requested date from URL parameter
$report_date = $_GET['date'] ?? $DEFAULT_DATE;

// Validate date format
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $report_date)) {
    $report_date = $DEFAULT_DATE;
}

// Load report data
$json_file = $REPORT_DIR . "/modulation_report_{$report_date}_web.json";

if (!file_exists($json_file)) {
    die("Report for {$report_date} not found. Please generate the report first.");
}

$report_data = json_decode(file_get_contents($json_file), true);

if (!$report_data) {
    die("Failed to load report data for {$report_date}");
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modulation Report - <?= htmlspecialchars($report_date) ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #eee;
        }
        .header h1 {
            color: #333;
            margin-bottom: 10px;
        }
        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }
        .card h3 {
            margin: 0 0 10px 0;
            font-size: 1.2em;
        }
        .card .value {
            font-size: 2em;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .card .label {
            opacity: 0.9;
            font-size: 0.9em;
        }
        
        .device-summary {
            margin-bottom: 30px;
        }
        .device-summary h2 {
            color: #333;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }
        .device-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 15px;
        }
        .device-card {
            border: 1px solid #ddd;
            border-radius: 6px;
            padding: 15px;
            background-color: #f9f9f9;
        }
        .device-card h4 {
            margin: 0 0 10px 0;
            color: #667eea;
        }
        
        .top-hoppers {
            margin-bottom: 30px;
        }
        .top-hoppers h2 {
            color: #333;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #667eea;
            color: white;
            font-weight: bold;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        
        .progress-bar {
            width: 100%;
            height: 20px;
            background-color: #e0e0e0;
            border-radius: 10px;
            overflow: hidden;
            margin: 5px 0;
        }
        .progress-fill {
            height: 100%;
            border-radius: 10px;
            transition: width 0.3s ease;
        }
        .qam64 { background-color: #4CAF50; }
        .qam16 { background-color: #FF9800; }
        .qpsk { background-color: #f44336; }
        
        .date-selector {
            text-align: center;
            margin-bottom: 20px;
        }
        .date-selector input {
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 4px;
            margin: 0 10px;
        }
        .date-selector button {
            padding: 8px 16px;
            background-color: #667eea;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .date-selector button:hover {
            background-color: #5a67d8;
        }
        
        .generated-info {
            text-align: center;
            color: #666;
            font-size: 0.9em;
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid #eee;
        }
        
        @media (max-width: 768px) {
            .summary-cards {
                grid-template-columns: 1fr;
            }
            .device-grid {
                grid-template-columns: 1fr;
            }
            table {
                font-size: 0.9em;
            }
            th, td {
                padding: 8px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Modulation Report</h1>
            <div class="date-selector">
                <form method="GET">
                    <input type="date" name="date" value="<?= htmlspecialchars($report_date) ?>">
                    <button type="submit">Load Report</button>
                </form>
            </div>
        </div>

        <!-- Summary Cards -->
        <div class="summary-cards">
            <div class="card">
                <h3>Total Upstreams</h3>
                <div class="value"><?= number_format($report_data['total_upstreams']) ?></div>
                <div class="label">Monitored Interfaces</div>
            </div>
            <div class="card">
                <h3>Total Hops</h3>
                <div class="value"><?= number_format($report_data['total_hops']) ?></div>
                <div class="label">Modulation Changes</div>
            </div>
            <?php if (isset($report_data['summary']['modulation_distribution'])): ?>
            <div class="card">
                <h3>QAM64 Usage</h3>
                <div class="value"><?= $report_data['summary']['modulation_distribution']['overall_qam64_pct'] ?>%</div>
                <div class="label">Overall Average</div>
            </div>
            <div class="card">
                <h3>QAM16 Usage</h3>
                <div class="value"><?= $report_data['summary']['modulation_distribution']['overall_qam16_pct'] ?>%</div>
                <div class="label">Overall Average</div>
            </div>
            <?php endif; ?>
        </div>

        <!-- Device Type Summary -->
        <?php if (isset($report_data['summary']['by_device_type']) && !empty($report_data['summary']['by_device_type'])): ?>
        <div class="device-summary">
            <h2>Summary by Device Type</h2>
            <div class="device-grid">
                <?php foreach ($report_data['summary']['by_device_type'] as $device): ?>
                <div class="device-card">
                    <h4><?= htmlspecialchars($device['device_type']) ?></h4>
                    <p><strong><?= number_format($device['total_upstreams']) ?></strong> upstreams</p>
                    <p><strong><?= number_format($device['total_hops']) ?></strong> total hops</p>
                    
                    <div>
                        QAM64: <?= $device['avg_qam64_pct'] ?>%
                        <div class="progress-bar">
                            <div class="progress-fill qam64" style="width: <?= $device['avg_qam64_pct'] ?>%"></div>
                        </div>
                    </div>
                    
                    <div>
                        QAM16: <?= $device['avg_qam16_pct'] ?>%
                        <div class="progress-bar">
                            <div class="progress-fill qam16" style="width: <?= $device['avg_qam16_pct'] ?>%"></div>
                        </div>
                    </div>
                    
                    <div>
                        QPSK: <?= $device['avg_qpsk_pct'] ?>%
                        <div class="progress-bar">
                            <div class="progress-fill qpsk" style="width: <?= $device['avg_qpsk_pct'] ?>%"></div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endif; ?>

        <!-- Top Hoppers Table -->
        <div class="top-hoppers">
            <h2>Top Hoppers (Interfaces with Most Modulation Changes)</h2>
            <table>
                <thead>
                    <tr>
                        <th>CMTS</th>
                        <th>Upstream</th>
                        <th>Hops</th>
                        <th>QAM64 %</th>
                        <th>QAM16 %</th>
                        <th>QPSK %</th>
                        <th>Measurements</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($report_data['summary']['top_hoppers'] as $row): ?>
                    <tr>
                        <td><?= htmlspecialchars($row['cmts']) ?></td>
                        <td><?= htmlspecialchars($row['upstream']) ?></td>
                        <td><strong><?= $row['hops'] ?></strong></td>
                        <td>
                            <span style="color: #4CAF50"><?= $row['qam64_pct'] ?>%</span>
                            <div class="progress-bar" style="width: 50px; height: 8px; display: inline-block; margin-left: 5px;">
                                <div class="progress-fill qam64" style="width: <?= $row['qam64_pct'] ?>%"></div>
                            </div>
                        </td>
                        <td>
                            <span style="color: #FF9800"><?= $row['qam16_pct'] ?>%</span>
                            <div class="progress-bar" style="width: 50px; height: 8px; display: inline-block; margin-left: 5px;">
                                <div class="progress-fill qam16" style="width: <?= $row['qam16_pct'] ?>%"></div>
                            </div>
                        </td>
                        <td>
                            <span style="color: #f44336"><?= $row['qpsk_pct'] ?>%</span>
                            <div class="progress-bar" style="width: 50px; height: 8px; display: inline-block; margin-left: 5px;">
                                <div class="progress-fill qpsk" style="width: <?= $row['qpsk_pct'] ?>%"></div>
                            </div>
                        </td>
                        <td><?= number_format($row['measurements']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="generated-info">
            Report generated at: <?= date('Y-m-d H:i:s', strtotime($report_data['generated_at'])) ?><br>
            Data for: <?= htmlspecialchars($report_data['report_date']) ?>
        </div>
    </div>

    <script>
        // Auto-refresh every 5 minutes if viewing today's report
        if ('<?= $report_date ?>' === '<?= date('Y-m-d') ?>') {
            setTimeout(function() {
                location.reload();
            }, 300000); // 5 minutes
        }
    </script>
</body>
</html>
