<?php
/**
 * Modulation Report Web Display
 * 
 * Displays the optimized modulation report data generated by 
 * modulation_report_generator.py in a nice web interface

 */

// Configuration
$REPORT_DIR = 'reports';
$DEFAULT_DATE = date('Y-m-d');

// Get requested date from URL parameter
$report_date = $_GET['date'] ?? $DEFAULT_DATE;

// Validate date format
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $report_date)) {
    $report_date = $DEFAULT_DATE;
}

// Load report data
$json_file = $REPORT_DIR . "/reports/modulation_report_{$report_date}_web.json";

if (!file_exists($json_file)) {
    die("Report for {$report_date} not found. Please generate the report first.");
}

$report_data = json_decode(file_get_contents($json_file), true);

if (!$report_data) {
    die("Failed to load report data for {$report_date}");
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modulation Report - <?= htmlspecialchars($report_date) ?></title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        'primary': '#667eea',
                        'secondary': '#764ba2'
                    }
                }
            }
        }
    </script>
</head>
<body class="bg-gray-50 min-h-screen" x-data="modulationReport()">
    <!-- Header -->
    <div class="bg-gradient-to-r from-primary to-secondary text-white shadow-lg">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
            <div class="flex flex-col sm:flex-row justify-between items-center">
                <div class="flex items-center mb-4 sm:mb-0">
                    <!-- VodafoneZiggo Logo -->
                    <div class="mr-6">
                        <svg width="60" height="60" viewBox="0 0 100 100" class="text-white">
                            <!-- VodafoneZiggo inspired logo -->
                            <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" stroke-width="3"/>
                            <circle cx="35" cy="35" r="12" fill="#E60000"/>
                            <circle cx="65" cy="35" r="12" fill="currentColor"/>
                            <path d="M25 65 Q50 85 75 65" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>
                            <text x="50" y="75" text-anchor="middle" font-size="10" fill="currentColor" font-weight="bold">VZ</text>
                        </svg>
                    </div>
                    <div>
                        <h1 class="text-3xl font-bold">Modulation Report</h1>
                        <p class="text-blue-100">Network Performance Analytics - VodafoneZiggo</p>
                    </div>
                </div>
                
                <!-- Date Selector -->
                <div class="flex items-center space-x-4">
                    <form method="GET" class="flex items-center space-x-2">
                        <i class="fas fa-calendar-alt"></i>
                        <input type="date" name="date" value="<?= htmlspecialchars($report_date) ?>" 
                               class="px-3 py-2 rounded-lg text-gray-800 border border-blue-200 focus:ring-2 focus:ring-blue-300">
                        <button type="submit" class="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg font-medium transition-colors">
                            <i class="fas fa-sync-alt mr-2"></i>Load
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        <!-- Summary Cards -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            <div class="bg-gradient-to-r from-blue-500 to-blue-600 p-6 rounded-xl shadow-lg text-white transform hover:scale-105 transition-transform">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-blue-100 text-sm font-medium">Total Upstreams</p>
                        <p class="text-3xl font-bold"><?= number_format($report_data['total_upstreams']) ?></p>
                        <p class="text-blue-200 text-xs">Monitored Interfaces</p>
                    </div>
                    <i class="fas fa-network-wired text-3xl text-blue-200"></i>
                </div>
            </div>

            <div class="bg-gradient-to-r from-purple-500 to-purple-600 p-6 rounded-xl shadow-lg text-white transform hover:scale-105 transition-transform">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-purple-100 text-sm font-medium">Total Hops</p>
                        <p class="text-3xl font-bold"><?= number_format($report_data['total_hops']) ?></p>
                        <p class="text-purple-200 text-xs">Modulation Changes</p>
                    </div>
                    <i class="fas fa-exchange-alt text-3xl text-purple-200"></i>
                </div>
            </div>

            <?php if (isset($report_data['summary']['modulation_distribution'])): ?>
            <div class="bg-gradient-to-r from-green-500 to-green-600 p-6 rounded-xl shadow-lg text-white transform hover:scale-105 transition-transform">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-green-100 text-sm font-medium">QAM64 Usage</p>
                        <p class="text-3xl font-bold"><?= $report_data['summary']['modulation_distribution']['overall_qam64_pct'] ?>%</p>
                        <p class="text-green-200 text-xs">Overall Average</p>
                    </div>
                    <i class="fas fa-signal text-3xl text-green-200"></i>
                </div>
            </div>

            <div class="bg-gradient-to-r from-orange-500 to-orange-600 p-6 rounded-xl shadow-lg text-white transform hover:scale-105 transition-transform">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-orange-100 text-sm font-medium">QAM16 Usage</p>
                        <p class="text-3xl font-bold"><?= $report_data['summary']['modulation_distribution']['overall_qam16_pct'] ?>%</p>
                        <p class="text-orange-200 text-xs">Overall Average</p>
                    </div>
                    <i class="fas fa-wifi text-3xl text-orange-200"></i>
                </div>
            </div>
            <?php endif; ?>
        </div>

        <!-- Device Type Summary -->
        <?php if (isset($report_data['summary']['by_device_type']) && !empty($report_data['summary']['by_device_type'])): ?>
        <div class="mb-8">
            <div class="flex items-center mb-6">
                <i class="fas fa-server text-2xl text-primary mr-3"></i>
                <h2 class="text-2xl font-bold text-gray-800">Summary by Device Type</h2>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <?php foreach ($report_data['summary']['by_device_type'] as $device): ?>
                <div class="bg-white p-6 rounded-xl shadow-lg border border-gray-100 hover:shadow-xl transition-shadow">
                    <div class="flex items-center mb-4">
                        <div class="bg-primary text-white p-3 rounded-lg mr-4">
                            <i class="fas fa-microchip text-xl"></i>
                        </div>
                        <h3 class="text-xl font-bold text-gray-800"><?= htmlspecialchars($device['device_type']) ?></h3>
                    </div>
                    
                    <div class="space-y-2 mb-4">
                        <div class="flex justify-between">
                            <span class="text-gray-600">Upstreams:</span>
                            <span class="font-semibold"><?= number_format($device['total_upstreams']) ?></span>
                        </div>
                        <div class="flex justify-between">
                            <span class="text-gray-600">Total Hops:</span>
                            <span class="font-semibold text-purple-600"><?= number_format($device['total_hops']) ?></span>
                        </div>
                    </div>
                    
                    <div class="space-y-3">
                        <div>
                            <div class="flex justify-between mb-1">
                                <span class="text-sm font-medium text-green-700">QAM64</span>
                                <span class="text-sm font-medium text-green-700"><?= $device['avg_qam64_pct'] ?>%</span>
                            </div>
                            <div class="w-full bg-gray-200 rounded-full h-2">
                                <div class="bg-green-500 h-2 rounded-full transition-all duration-300" 
                                     style="width: <?= $device['avg_qam64_pct'] ?>%"></div>
                            </div>
                        </div>
                        
                        <div>
                            <div class="flex justify-between mb-1">
                                <span class="text-sm font-medium text-orange-700">QAM16</span>
                                <span class="text-sm font-medium text-orange-700"><?= $device['avg_qam16_pct'] ?>%</span>
                            </div>
                            <div class="w-full bg-gray-200 rounded-full h-2">
                                <div class="bg-orange-500 h-2 rounded-full transition-all duration-300" 
                                     style="width: <?= $device['avg_qam16_pct'] ?>%"></div>
                            </div>
                        </div>
                        
                        <div>
                            <div class="flex justify-between mb-1">
                                <span class="text-sm font-medium text-red-700">QPSK</span>
                                <span class="text-sm font-medium text-red-700"><?= $device['avg_qpsk_pct'] ?>%</span>
                            </div>
                            <div class="w-full bg-gray-200 rounded-full h-2">
                                <div class="bg-red-500 h-2 rounded-full transition-all duration-300" 
                                     style="width: <?= $device['avg_qpsk_pct'] ?>%"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endif; ?>

        <!-- Top Hoppers Section -->
        <div class="bg-white rounded-xl shadow-lg border border-gray-100 mb-8">
            <div class="p-6 border-b border-gray-200">
                <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                    <div class="flex items-center mb-4 sm:mb-0">
                        <i class="fas fa-trophy text-2xl text-yellow-500 mr-3"></i>
                        <h2 class="text-2xl font-bold text-gray-800">Top Hoppers</h2>
                        <span class="ml-2 px-2 py-1 bg-yellow-100 text-yellow-800 text-xs rounded-full">
                            Most Modulation Changes
                        </span>
                    </div>
                    
                    <!-- Search and Filters -->
                    <div class="flex flex-col sm:flex-row space-y-2 sm:space-y-0 sm:space-x-4">
                        <div class="relative">
                            <i class="fas fa-search absolute left-3 top-3 text-gray-400"></i>
                            <input type="text" x-model="searchTerm" placeholder="Search CMTS or Upstream..." 
                                   class="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent w-full sm:w-64">
                        </div>
                        <select x-model="deviceFilter" class="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent">
                            <option value="">All Devices</option>
                            <option value="CCAP0">CCAP0xx</option>
                            <option value="CCAP1">CCAP1xx</option>
                            <option value="CCAP2">CCAP2xx</option>
                        </select>
                        <select x-model="hopFilter" class="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent">
                            <option value="">All Hops</option>
                            <option value="high">High (>50)</option>
                            <option value="medium">Medium (10-50)</option>
                            <option value="low">Low (<10)</option>
                        </select>
                    </div>
                </div>
            </div>
            
            <!-- Table -->
            <div class="overflow-x-auto">
                <table class="min-w-full">
                    <thead class="bg-gradient-to-r from-primary to-secondary text-white">
                        <tr>
                            <th class="px-6 py-4 text-left text-sm font-semibold cursor-pointer hover:bg-blue-700 transition-colors" 
                                @click="sortBy('cmts')">
                                <div class="flex items-center">
                                    CMTS
                                    <i class="fas fa-sort ml-2 opacity-50"></i>
                                </div>
                            </th>
                            <th class="px-6 py-4 text-left text-sm font-semibold cursor-pointer hover:bg-blue-700 transition-colors" 
                                @click="sortBy('upstream')">
                                <div class="flex items-center">
                                    Upstream
                                    <i class="fas fa-sort ml-2 opacity-50"></i>
                                </div>
                            </th>
                            <th class="px-6 py-4 text-left text-sm font-semibold cursor-pointer hover:bg-blue-700 transition-colors" 
                                @click="sortBy('hops')">
                                <div class="flex items-center">
                                    Hops
                                    <i class="fas fa-sort ml-2 opacity-50"></i>
                                </div>
                            </th>
                            <th class="px-6 py-4 text-left text-sm font-semibold">QAM64 %</th>
                            <th class="px-6 py-4 text-left text-sm font-semibold">QAM16 %</th>
                            <th class="px-6 py-4 text-left text-sm font-semibold">QPSK %</th>
                            <th class="px-6 py-4 text-left text-sm font-semibold cursor-pointer hover:bg-blue-700 transition-colors" 
                                @click="sortBy('measurements')">
                                <div class="flex items-center">
                                    Measurements
                                    <i class="fas fa-sort ml-2 opacity-50"></i>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                        <template x-for="(row, index) in filteredData" :key="index">
                            <tr class="hover:bg-gray-50 transition-colors cursor-pointer" 
                                @click="selectedRow = selectedRow === index ? null : index"
                                :class="selectedRow === index ? 'bg-blue-50 border-l-4 border-primary' : ''">
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center">
                                        <div class="w-3 h-3 rounded-full mr-3" 
                                             :class="getDeviceColor(row.cmts)"></div>
                                        <span class="font-medium text-gray-900" x-text="row.cmts"></span>
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-gray-900" x-text="row.upstream"></td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <span class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium"
                                          :class="getHopBadgeColor(row.hops)"
                                          x-text="row.hops">
                                    </span>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center space-x-2">
                                        <span class="font-medium text-green-700" x-text="row.qam64_pct + '%'"></span>
                                        <div class="w-16 bg-gray-200 rounded-full h-2">
                                            <div class="bg-green-500 h-2 rounded-full transition-all duration-300" 
                                                 :style="`width: ${row.qam64_pct}%`"></div>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center space-x-2">
                                        <span class="font-medium text-orange-700" x-text="row.qam16_pct + '%'"></span>
                                        <div class="w-16 bg-gray-200 rounded-full h-2">
                                            <div class="bg-orange-500 h-2 rounded-full transition-all duration-300" 
                                                 :style="`width: ${row.qam16_pct}%`"></div>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center space-x-2">
                                        <span class="font-medium text-red-700" x-text="row.qpsk_pct + '%'"></span>
                                        <div class="w-16 bg-gray-200 rounded-full h-2">
                                            <div class="bg-red-500 h-2 rounded-full transition-all duration-300" 
                                                 :style="`width: ${row.qpsk_pct}%`"></div>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-gray-900" x-text="new Intl.NumberFormat().format(row.measurements)"></td>
                            </tr>
                        </template>
                        
                        <template x-if="filteredData.length === 0">
                            <tr>
                                <td colspan="7" class="px-6 py-12 text-center text-gray-500">
                                    <i class="fas fa-search text-4xl mb-4 opacity-50"></i>
                                    <p class="text-lg">No results found</p>
                                    <p class="text-sm">Try adjusting your search or filter criteria</p>
                                </td>
                            </tr>
                        </template>
                    </tbody>
                </table>
            </div>
            
            <!-- Pagination -->
            <div class="px-6 py-4 border-t border-gray-200">
                <div class="flex items-center justify-between">
                    <div class="text-sm text-gray-700">
                        Showing <span x-text="((currentPage - 1) * itemsPerPage) + 1"></span> to 
                        <span x-text="Math.min(currentPage * itemsPerPage, filteredData.length)"></span> of 
                        <span x-text="filteredData.length"></span> results
                    </div>
                    <div class="flex space-x-2">
                        <button @click="currentPage = Math.max(1, currentPage - 1)" 
                                :disabled="currentPage === 1"
                                :class="currentPage === 1 ? 'opacity-50 cursor-not-allowed' : 'hover:bg-gray-100'"
                                class="px-3 py-2 border border-gray-300 rounded-lg transition-colors">
                            <i class="fas fa-chevron-left"></i>
                        </button>
                        <span class="px-4 py-2 bg-primary text-white rounded-lg" x-text="currentPage"></span>
                        <button @click="currentPage = Math.min(Math.ceil(filteredData.length / itemsPerPage), currentPage + 1)" 
                                :disabled="currentPage >= Math.ceil(filteredData.length / itemsPerPage)"
                                :class="currentPage >= Math.ceil(filteredData.length / itemsPerPage) ? 'opacity-50 cursor-not-allowed' : 'hover:bg-gray-100'"
                                class="px-3 py-2 border border-gray-300 rounded-lg transition-colors">
                            <i class="fas fa-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <div class="bg-white rounded-xl shadow-lg border border-gray-100 p-6 text-center text-gray-600">
            <div class="flex items-center justify-center space-x-6 mb-4">
                <div class="flex items-center">
                    <i class="fas fa-clock text-primary mr-2"></i>
                    <span>Generated: <?= date('Y-m-d H:i:s', strtotime($report_data['generated_at'])) ?></span>
                </div>
                <div class="flex items-center">
                    <i class="fas fa-calendar text-primary mr-2"></i>
                    <span>Data for: <?= htmlspecialchars($report_data['report_date']) ?></span>
                </div>
                <div class="flex items-center">
                    <i class="fas fa-sync-alt text-primary mr-2"></i>
                    <span class="text-xs" x-show="autoRefresh">Auto-refresh: ON</span>
                </div>
            </div>
            <div class="text-sm text-gray-500 border-t pt-4">
                <span>Expert Engineer Access Engineering | Network & Technology - Access & Transport</span><br>
                <span class="text-xs">© <?= date('Y') ?> VodafoneZiggo - Automated Network Monitoring System</span>
            </div>
        </div>
    </div>

    <!-- Alpine.js Component -->
    <script>
        function modulationReport() {
            return {
                searchTerm: '',
                deviceFilter: '',
                hopFilter: '',
                sortField: 'hops',
                sortDirection: 'desc',
                currentPage: 1,
                itemsPerPage: 20,
                selectedRow: null,
                autoRefresh: '<?= $report_date ?>' === '<?= date('Y-m-d') ?>',
                
                data: <?= json_encode($report_data['summary']['top_hoppers']) ?>,
                
                get filteredData() {
                    let filtered = this.data;
                    
                    // Search filter
                    if (this.searchTerm) {
                        const search = this.searchTerm.toLowerCase();
                        filtered = filtered.filter(row => 
                            row.cmts.toLowerCase().includes(search) || 
                            row.upstream.toString().includes(search)
                        );
                    }
                    
                    // Device filter
                    if (this.deviceFilter) {
                        filtered = filtered.filter(row => 
                            row.cmts.startsWith(this.deviceFilter)
                        );
                    }
                    
                    // Hop filter
                    if (this.hopFilter) {
                        filtered = filtered.filter(row => {
                            if (this.hopFilter === 'high') return row.hops > 50;
                            if (this.hopFilter === 'medium') return row.hops >= 10 && row.hops <= 50;
                            if (this.hopFilter === 'low') return row.hops < 10;
                            return true;
                        });
                    }
                    
                    // Sort
                    filtered.sort((a, b) => {
                        let aVal = a[this.sortField];
                        let bVal = b[this.sortField];
                        
                        if (typeof aVal === 'string') {
                            aVal = aVal.toLowerCase();
                            bVal = bVal.toLowerCase();
                        }
                        
                        if (this.sortDirection === 'asc') {
                            return aVal > bVal ? 1 : -1;
                        } else {
                            return aVal < bVal ? 1 : -1;
                        }
                    });
                    
                    // Pagination
                    const start = (this.currentPage - 1) * this.itemsPerPage;
                    return filtered.slice(start, start + this.itemsPerPage);
                },
                
                sortBy(field) {
                    if (this.sortField === field) {
                        this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
                    } else {
                        this.sortField = field;
                        this.sortDirection = 'desc';
                    }
                    this.currentPage = 1;
                },
                
                getDeviceColor(cmts) {
                    if (cmts.startsWith('CCAP0')) return 'bg-blue-500';
                    if (cmts.startsWith('CCAP1')) return 'bg-green-500';
                    if (cmts.startsWith('CCAP2')) return 'bg-purple-500';
                    return 'bg-gray-500';
                },
                
                getHopBadgeColor(hops) {
                    if (hops > 50) return 'bg-red-100 text-red-800';
                    if (hops > 20) return 'bg-orange-100 text-orange-800';
                    if (hops > 10) return 'bg-yellow-100 text-yellow-800';
                    return 'bg-green-100 text-green-800';
                },
                
                init() {
                    // Auto-refresh every 5 minutes for today's report
                    if (this.autoRefresh) {
                        setTimeout(() => {
                            location.reload();
                        }, 300000);
                    }
                }
            }
        }
    </script>
</body>
</html>
